#!/usr/bin/perl
# Blosxom Plugin: moreentries    -*- perl -*-
# Author(s): Jason Clark
# Blosxom Home/Docs/Licensing: http://www.blosxom.com
# moreentries plugin Home/Docs/Licensing: 
#     http://jclark.org/weblog/WebDev/Blosxom/plugins/moreentries
#
# Version 0.4.3
# Modified 17-Apr-2015 Nick Leverton <nick@leverton.org>
# Fix deprecated if defined(@array) calls, just use if (@array) to reduce noise
# from Perl in error.log
#
# Version 0.4.2
# Modified 27-Mar-2010 Nick Leverton <nick@leverton.org>
# Replace blosxom::self_url by blosxom::url/$blosxom::path_info.
#   Thanks to Carsten Agger <agger@c.dk>

# Version 0.4.1
# Modified 20-Sep-2008 Nick Leverton <nick@leverton.org>
# Use &amp; instead of naked & for adding the _start parameter to existing query

# Version 0.4
# Modified 05-Jun-2008 Nick Leverton <nick@leverton.org>
# Quote path regexp with \Q to avoid interpolation problems in special characters.
# Fixup for use warnings, use strict and make module-safe by qualifying blosxom:: names.
# Add $prevcount in case we weren't starting with a multiple of num_entries stories.
#
# Version 0.3
# Modified 16-Feb-2008 Steve Schwarz
# Corrected open <img> tag for right.gif
# Changed selfstyle so style tag need only be configured in one place
# 
# Version 0.2
# Modified 21-Oct-2004 Steve Schwarz
# http://tech.agilitynerd.com/blog/web/blogging/blosxom/moreentries_mods.html
#
# Added page index feature - 
# a configurable number of text and/or graphic links to pages preceding and
# following the current page. This way users can jump more than $num_entries
# forward or backward at a time. I've tried to make it flexible to configurable.
#
package moreentries;

use warnings;
use strict;

# --- Configurable variables -----

use vars qw/ $selfstyle /;
use vars qw/ $numpagelinks $textlinks $imagelinks $prevlinkimage $nextlinkimage /;
use vars qw/ $currentpageimage @pageimages /;

# Set to the style to add to $moreentries::links will have simple style attribs
$selfstyle = 'style="padding: 0 3px;"'; # set to '' for no style

# Variables that control how page links are created.
# HTML is generated into $moreentries::pagelinks
# How many page links if any should be created - 0 is none
$numpagelinks = 10;

# Control which types of links are created.
$textlinks = 1;		# set to 1 to enable text links 0 to disable
$imagelinks = 1;	# set to 1 to enable image links 0 to disable

# Define an image file to be displayed above the $prevlink
$prevlinkimage = "/images/left.gif";
# Define an image file to be displayed above the $nextlink 
$nextlinkimage = "/images/right.gif";
# Define an image file to be displayed above the current page
$currentpageimage = "/images/ball.red.gif";

# Define an array of images to use above each page number link
# the images will be repeated in the order they are placed in the array:
# Same image above each page link:
@pageimages = qw( /images/ball.gray.gif );
# Alternating images above each page link:
# @pageimages = qw( /images/ball.red.gif /images/ball.gray.gif );

# --- Control variables -----

use vars qw/ $active $totalposts $start $end $prevlink $nextlink $prevcount $nextcount $links /;
use vars qw/ $totalpages $currentpage $pagelinks /;

# --- Template variables -----

# none

# --------------------------------

sub start {
  return 1;
}

sub filter {
  # moreentries has some special requirements we're going to
  # address here:
  #  * must be last filter to run - we'll check our pos in 
  #    @blosxom::plugins.  If we're not last, move us and
  #    exit, otherwise procede
  #  * need to operate on sorted entries - since sort()
  #    hasn't run yet, and isn't even defined yet, we'll
  #    have to mimic blosxom's behavior, i.e, find and run
  #    the apropriate plugin's sort()
    my ($self, $files, $others) = @_;
    $active = undef;
    $start = $end = $prevlink = $nextlink = undef;
    # $num_entries is ignored for date-based urls, or if num_entries not in use
    return 1 if (defined $blosxom::path_info_yr && $blosxom::path_info_yr =~ /\d/)
             or !defined($blosxom::num_entries) or $blosxom::num_entries < 1;
    my $pos;
    for(my $i=0;$i<@blosxom::plugins;$i++) { 
        if($blosxom::plugins[$i] eq 'moreentries') {
            $pos=$i;
            last;
        }
    }
    return 0 unless $pos;
    unless ($pos==$#blosxom::plugins) {
        #we're not last plugin, so move us
        splice @blosxom::plugins, $pos, 1;
        push @blosxom::plugins, 'moreentries';
        return 1;
    }
    #made it this far, time to do our stuff.  First, do we need to?
    #filter out posts outside of requested path
    my $currentdir = $blosxom::path_info;
    if ( $currentdir =~ /(.*?)([^\/]+)\.(.+)$/ and $2 ne 'index' ) {
      $currentdir = "$1$2.$blosxom::file_extension";
    } 
    else { 
      $currentdir =~ s!/index\..+$!!;
    }

    foreach my $path_file (keys %{$files}) {
        my ($path,$fn) = $path_file =~ m!^$blosxom::datadir/(?:(.*)/)?(.*)\.$blosxom::file_extension!;
        # Only stories in the right hierarchy
        next if (defined $path && $path =~ /^\Q$currentdir/) or $path_file eq "$blosxom::datadir/$currentdir";
	#print STDERR "path='$path', fn='$fn', curdir='$currentdir', pathfile='$path_file', ddir='$blosxom::datadir'\n";
        delete $files->{$path_file};
    }

    $totalposts = scalar(keys %{$files});
    #print STDERR "TOTALPOSTS='$totalposts'\n";    

    return 1 if $totalposts <= $blosxom::num_entries;

    #guess we do.
    $active = 1;
    
    # Define a default sort subroutine
    my $sort = sub {
      my($files_ref) = @_;
      return sort { $files_ref->{$b} <=> $files_ref->{$a} } keys %$files_ref;
    };
    
    # Allow for the first encountered plugin::sort subroutine to override the
    # default built-in sort subroutine
    my $tmp; 
    foreach my $plugin ( @blosxom::plugins ) { 
        if ($blosxom::plugins{$plugin} > 0 and $plugin->can('sort')) {
            if (defined($tmp = $plugin->sort())) {
                $sort = $tmp;
                last;
             }
        }
    }
  
    my @sorted = &$sort($files, $others);
    $start = (blosxom::param("_start") or 1);
    $end = $start + $blosxom::num_entries -1;
    $end = $totalposts if $end > $totalposts;
    
    #trim %files
    for (my $i=0;$i<$start-1;$i++) {
        delete $files->{$sorted[$i]};
    }
    for (my $i=$end; $i<$totalposts; $i++) {
        delete $files->{$sorted[$i]};
    }
    
    #setup prevlink, nextlink
    my $url = $blosxom::url."/".$blosxom::path_info;
    $url =~ s/[&\?;]_start=\d+//g;
    $url =~ s/[&?;]-\w+=\d+//g;
    $url =~ s/\?\s*$//;

    my $appendchar = $url =~ /\?/ ? "&amp;" : "?";
    my $prev = $start - $blosxom::num_entries;
    $prev = 1 if $prev < 0;
    my $next = $end + 1;
    $prevlink = "$url${appendchar}_start=$prev" if $start > 1;
    $nextlink = "$url${appendchar}_start=$next" if $end < $totalposts;
    $prevcount = $start - $prev;
    $nextcount = $totalposts - $end;
    $nextcount = $blosxom::num_entries if $nextcount > $blosxom::num_entries;
    $links = "<div class='moreentries'><span class='prevlink' $selfstyle>";
    if (defined($prevlink)) { 
	$links .= "<a href='$prevlink'>Previous $prevcount entries</a> "; 
	# only add nextlink span if there is a prevlink this causes next to float left instead of right
	$links .= "</span><span class='nextlink' $selfstyle>";
    }
    if (defined($nextlink)) { $links .= " <a href='$nextlink'>Next $nextcount entries</a>"; }
    $links .= "</span></div>";
    
    if ($numpagelinks > 0 and ($textlinks or $imagelinks)) {
	# setup page information
	use POSIX;
	$currentpage = ceil($start / $blosxom::num_entries);
	$currentpage = 1 if $currentpage <= 0;
	$totalpages = ceil($totalposts / $blosxom::num_entries);
	$totalpages = 1 if $totalpages <= 0;

	# generate HTML for links to pages - generate at most 10 links plus next & previous
	my $startpage = 1;
	$startpage = $currentpage - floor($numpagelinks / 2) if ($currentpage > floor($numpagelinks/2));
	my $endpage = $startpage + $numpagelinks-1;
	$endpage = $totalpages if ($endpage > $totalpages);

	# reset self styling
 	$pagelinks = "<div class='pagelinks' $selfstyle>";
 	$pagelinks .= "<table border='0' cellpadding='0' cellspacing='0' align='center' $selfstyle>";
	my( $imagelinkhtml, $textlinkhtml );
	# Insert link to previous page if it exists
 	if (defined($prevlink)) {
	     if ($textlinks) {
		 $textlinkhtml = "<td $selfstyle align='right'><a href='$prevlink'>Previous $blosxom::num_entries articles</a></td>";
	     } else {
		 $textlinkhtml = "<td $selfstyle/>";
	     }
	     if (defined($prevlinkimage)) {
		 $imagelinkhtml = "<td $selfstyle align='right'><a href='$prevlink' style='border-bottom:none'><img src='$prevlinkimage'/></a></td>";
	     } else {
		 $imagelinkhtml = "<td $selfstyle/>";
	     }
	 } else { # since I'm centering I need to add the same space as hidden
	     $textlinkhtml = "<td style='visibility:hidden'>Previous $blosxom::num_entries articles</td>";
	     $imagelinkhtml = "<td/>";
	 }
	# generate text and/or image links for each page in the configured range
	for (my $page=$startpage; $page<=$endpage; $page++) {
	    if ($page != $currentpage) {
		my $link .= "$url${appendchar}_start=" . ((($page-1) * $blosxom::num_entries) + 1);
		if ($imagelinks and (@pageimages)) {
		    $imagelinkhtml .= "<td $selfstyle><a href='$link' style='border-bottom:none'>" .
			"<img src='$pageimages[$page % ($#pageimages+1)]'/></a></td>";
		} elsif ($textlinks) {
		    $imagelinkhtml .= "<td $selfstyle/>";
		}
		if ($textlinks) {
		    $textlinkhtml .=  "<td $selfstyle><a href='$link' $selfstyle>$page</a></td>";
		} elsif ($imagelinks) {
		    $textlinkhtml .=  "<td $selfstyle/>";
		}

	    } else {	# no link for the current page
		if ($imagelinks and (defined($currentpageimage) or (@pageimages))) {
		    if (defined($currentpageimage)) {
			$imagelinkhtml .= "<td $selfstyle><img src='$currentpageimage'/></td>";
		    } elsif (@pageimages) {
			$imagelinkhtml .= "<td $selfstyle><img src='$pageimages[$page % ($#pageimages+1)]'/></td>"
		    }
		} elsif ($textlinks) {
		    $imagelinkhtml .= "<td $selfstyle/>";
		}
		if ($textlinks) {
		    $textlinkhtml .= "<td $selfstyle><span style='color:red'>$page</span></td>";
		} elsif ($imagelinks) {
		    $textlinkhtml .=  "<td $selfstyle/>";
		}
	    }
	}

 	# Insert link and/or image to next page if it exists
 	if (defined($nextlink)) {
	     if ($textlinks) {
		 $textlinkhtml .= "<td $selfstyle align='left'><a href='$nextlink'>Next $blosxom::num_entries articles</a></td>";
	     }
	     else {
		 $textlinkhtml .= "<td $selfstyle/>";
	     }
	     if (defined($nextlinkimage)) {
		 $imagelinkhtml .= "<td $selfstyle align='left'><a href='$nextlink' style='border-bottom:none'><img src='$nextlinkimage'/></a></td>";
	     }
	     else {
		 $imagelinkhtml .= "<td $selfstyle/>";
	     }
	 } else { # since I'm centering I need to add the same space as hidden
	     $textlinkhtml .= "<td style='visibility:hidden'>&nbsp;Next $blosxom::num_entries articles</td>";
	     $imagelinkhtml .= "<td/>";
	 }

	# Now plugin created table rows
	$pagelinks .= "<tr align='center'>";
#	$pagelinks .= "<td rowspan='2'>Pages:</td>";
	if ($imagelinks) {
	    $pagelinks .= $imagelinkhtml . "</tr>";
	    $pagelinks .= "<tr align='center'>" if ($textlinks);
	}
	$pagelinks .= $textlinkhtml . "</tr>" if ($textlinks);

	$pagelinks .= "</table>";
	$pagelinks .= "</div>";
    }
    return 1;  


}

sub sort() {
    return undef;
}

1;

__END__

=head1 Name

Blosxom Plug-In: moreentries

=head1 Synopsis

When the Blosxom variable $num_entries is set to a non-zero number,
Any non-date style request(category or root url) will only display
$num_entries entries on the page.  No method is provided to see
subsequent entries (aside from using date-urls to browse back in time,
and this can't be combined with categories).

moreentries enables these addional entries to be viewed.  moreentries adds
the ability for blosxom urls to accept an _start parameter, for example:

  http://jclark.org/weblog/index.html?_start=11

Will show you all the weblog entries *after* the first 10.  moreentries also 
offers several variable to allow you to add Next and Previous links to your
templates, and to show the current range of posts, and total posts.

PLEASE NOTE: Probably doens't work with static rendering.  Untested.

=head2 Quick Start

Just drop it in your $plugin_dir.  There is only one config variable, which 
we will ignore for the quick start; see next section for more info.  You'll
need to modify your head or foot template to see the links.  For a quick
start, add $moreentries::links to your head or foot template.  And of course,
your blosxom.cgi must have a (nonzero) value set for $num_entries.

That's it; you should now have next & previous functionality.

To enable paged access set the $moreentries::numpagelinks to a non-zero value 
to control how many links to pages preceding and following the current page 
will be generated. Add the $moreentries::pagelinks to your head or foot 
template to see the links. You can use this independently from 
$moreentries::links.

=head1 More Info

moreentries exposes the following variables for use in your templates.  None of 
these are per-story, and are generally suited for use in your head or foot template.

$moreentries::active - true if the plugin is 'in use'.  This will be false if
the url is a date url (blosxom ignores $num_entries), or if there are not at 
least $num_entries entries matching the request, or if $num_entries is not set.
$moreentries::totalposts - total number of entries that match the request
$moreentries::start - the number of the first entry being displayed
$moreentries::end  - the number of the last entry being displayed
$moreentries::links - inserts (x)HTML containing links to the previous and
next batch of entries.  If one (or both) of these links does not apply ( for example,
when viewing the first batch of entries, there are no previous entries) there
is no link.

The output of $moreentries::links will look like this:
 <div class='moreentries'>
   <span class='prevlink' style='padding:0 15px'><a href='http://127.0.0.1/weblog/index.html?_start=1'>Previous 10 entries</a></span>
   <span class='nextlink' style='padding:0 15px'><a href='http://127.0.0.1/weblog/index.html?_start=21'>Next 10 entries</a></span>
 </div>
 
The embedded style prevents the links from being right next to each other.  This output
is sufficient for a quick drop-in.  If you'd like to control CSS styles yourself, 
there is a config variable ( $selfstyle ) that controls this, just set it to 0.

If you want even more control over your output, there are some additional variables
you can use:

$moreentries::prevlink - if $moreentries::start is not 1, this will contain an
URL to move to the previous batch of entries.  Will be undef if no Previous batch
(i.e., $moreentries::start =1)

$moreentries::prevcount - If there is a previous batch, this contains the number of posts
in it.  This is normally $num_entries, except when there arent enough entries.  For example,
if this batch starts at post 21 in the Rants category, and your $num_entries is 15, then
$morrentries::prevcount will be 5.

$moreentries::nextlink - if $moreentries::end < $morrentries::totalposts, this will
contain an URL to the next batch of entries.  Will be undef if no Next batch
(i.e., $moreentries::end = $moreentries::totalposts)

$moreentries::nextcount - If there is a next batch, this contains the number of posts
in it.  This is normally $num_entries, except when there arent enough entries left.  For
example, if there are 12 posts in the Rants category, and your $num_entries is 10, then
$morrentries::nextcount will be 2.

There are a number of config variables, explained above in the discussion of $moreentries::links:

$moreentries::selfstyle - when set, $moreentries::links will contain the specified style attributes.

The page links feature has its own configuration variables. The $moreentries::selfstyle
variable is also applied to the $moreentries::pagelinks.

$moreentries::numpagelinks - when set, $moreentries::pagelinks will be
created and contain the number of links specified by this
variable. The current page will be centered in the links if possible.

$moreentries::textlinks - when set to 1 enables text links to
preceding and following pages. It can be used independently or combined with 
the $moreentries::imagelinks setting. The html generated if of the format:

<div class='pagelinks' style='padding:0 5px'>
<table border='0' cellpadding='0' cellspacing='0' align='center' style='padding:0 5px'>
<tr align='center'><td rowspan='2'>Pages:</td>
<td style='padding:0 5px'><a href='http://localhost/cgi-bin/blosxom.cgi?_start=1'>Previous</a></td>
<td style='padding:0 5px'><a href='http://localhost/cgi-bin/blosxom.cgi?_start=1' style='padding:0 5px'>1</a></td>
<td style='padding:0 5px'>2</td>
<td style='padding:0 5px'><a href='http://localhost/cgi-bin/blosxom.cgi?_start=21' style='padding:0 5px'>3</a>
...
<td style='padding:0 5px'><a href='http://localhost/cgi-bin/blosxom.cgi?_start=5'>Next</a></td>
</tr></table></div>

$moreentries::imagelinks - when set to 1 enables images links to preceding and
following pages. It can be used independently or combined with 
the $moreentries::textlinks setting. The html generated if of the format:

<div class='pagelinks' style='padding:0 5px'>
<table border='0' cellpadding='0' cellspacing='0' align='center' style='padding:0 5px'>
<tr align='center'><td rowspan='2'>Pages:</td>
<td style='padding:0 5px'><a href='http://localhost/cgi-bin/blosxom.cgi?_start=1' style='border-bottom:none'>
<img src='/images/left.gif'/></a></td>
<td style='padding:0 5px'><img src='/images/text.gif'/></td>
<td style='padding:0 5px'><a href='http://localhost/cgi-bin/blosxom.cgi?_start=21' style='border-bottom:none'>
<img src='/images/right.gif'/></a></td></tr></table></div>

Where the images used are specified in the following variables:

$moreentries::prevlinkimage - defines an image file to be displayed in a link
to the previous page. If not defined no image link is created.

$moreentries::nextlinkimage - defines an image file to be displayed in a link 
to the next page. If not defined no image link is created.

$moreentries::currentpageimage - defines an image file to be displayed in a link
to the current page. If not specified an image from @moreentries::pageimages is used.

@moreentries::pageimages - defines an array of images to use for each page number link.  
The images will be repeated in the order they are placed in the array.

The pagelink feature adds the following variables for your programming pleasure:
$moreentries::totalpages - the number of pages in the site.
$moreentres::currentpage - the current page number .
$moreentries::pagelinks - the html contain the generated text and/or image links

=head1 Internals

This is a big ugly hack.  The only entrypoint that worked for this is the filter() hook;
the problem is that when filter() is called, the sort() routine hasn't run (isn't even
decided on yet!), and %files contains all posts, not just the ones matching the request.
Even running as filter, it has to be the last plugin to run, so that any other filtering 
happens before we decide the 'numbering' of the posts.

The way it works:  when filter() is called, we check @plugins to see if moreentries is
the last plugin.  If not, we munge @plugins, making us the last plugin, and return.  If
we are the last plugin (as we eventually will be), then we proceed.  

The next step is rather inefficient:  we have to sort %files to number them, so we
check all plugins for a sort() routine, providing a default if none is found.  This
code is stolen wholesale from blosxom.cgi.  Once they are sorted, we get rid of all
files that don't match the request url (anything in the wrong category, essentially).
This code is also stolen from blosxom.cgi, with a couple of adjustments.

Finally, we delete all the posts before our start (as provided by the param _start), and
all posts after our ending post.  Thus, when filter is done, %files only contains the posts
that will be displayed.  This makes redundant much of the code that runs in blosxom after this.


=head1 Version

0+4i

=head1 Author

Jason Clark  (jason@jclark.org; http://jclark.org/weblog)

=head1 Acknowledgements

Thanks to Fletcher T. Penny (http://fletcher.freeshell.org/) for helping test the plugin.

=head1 See Also

Blosxom Home/Docs/Licensing: http://blosxom.sourceforge.net

Blosxom Plugin Docs: http://blosxom.sourceforge.net/documentation/users/plugins.html

=head1 Bugs

This whole thing is a big hack, see the Internals section above for some info.
This should probably be implemented as part of the core Blosxom application.

Not tested at all with static rendering, probably won't work.

=head1 License

This Blosxom Plug-in Copyright 2003, Jason Clark

(This license is the same as Blosxom's)
Permission is hereby granted, free of charge, to any person obtaining a copy 
of this software and associated documentation files (the "Software"), to deal 
in the Software without restriction, including without limitation the rights 
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
copies of the Software, and to permit persons to whom the Software is furnished 
to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

