# ----- atomfeed configurable variables -----
 
# Who would you like your feed to credit as the default author of each entry? 
# Leave blank and the atomfeed plugin will attempt to use the whoami and
# fauxami plugins
$atomfeed::default_author = "Nick Leverton";

# What year was your weblog started?  This will be used 
# to form part of your weblog's unique ID.
$atomfeed::feed_yr = "2007";

# What is the default author's email address?
# Leave blank to exclude.
$atomfeed::author_email = 'nick@leverton.org';

# Icon
# Put the URL for a site icon here (for example, your site's favicon).  Leave blank to exclude.
$atomfeed::icon_url = "https://www.leverton.org/favicon.ico";

# Logo
# Set to the URL for your site logo.  Leave blank to exclude.
$atomfeed::logo_url = "https://www.leverton.org/hareruns.gif";

# ----- nixie configurable variables -----

#  Should nixie throw a "real" 404?
#     When set to 0 (normal), the plugin adds your "file not found"
#     message to the normal blosxom page; when set to 1, the entire
#     blosxom page is dumped -- including http header -- and a new
#     page is generated with header status set to 404.

$nixie::throw_a_real_404 = 1;

# ----- storytitle configurable variables -----

# default separator to add to story title

$storytitle::sep = ' : ';

# do we default to the right aligned title
# 1 for right aligned, 0 for left

$storytitle::right = 1;

# separator for right aligned title 

$storytitle::right_sep = undef;

# separator for left aligned title

$storytitle::left_sep = undef;


$storytitle::add_blogtitle_to_indexes = 1;
$storytitle::add_blogtitle_to_story = 1;

$textile2::flavor = "html";
